title = "My Server"
icon_path = "default_icon.png"
admin_public_keys = []
file_path = "./files"

public_https_address = "my-server.com"
public_ipv4_address = "0.0.0.0"
public_ipv6_address = "::"

[[ice_servers]]
urls = ["stun:stun.l.google.com:19302"]

[[ice_servers]]
urls = ["turn:turn.example.com:3478"]
username = "my-username"
credential = "my-credential"
